
language: python

before_install:
 - sudo apt-get update
 - sudo apt-get install cmake
 - sudo apt-get install build-essential cmake git libgtk2.0-dev pkg-config libdc1394-22

install:
 - "pip install --pre -r requirements.txt"

python:
 - "3.4"
script:
 - sh -x test/opencv3_setup.sh
 - python main.py
