dist: trusty

language: python

before_install:
 - sudo apt-get update
 - sudo apt-get install cmake
 - sudo apt-get install build-essential cmake git libgtk2.0-dev pkg-config libdc1394-22 libdc1394-22-dev libjpeg-dev libpng12-dev libtiff4-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libxine-dev libv4l-dev libtbb-dev libqt4-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libblas-dev libatlas-dev libatlas-base-dev x264 v4l-utils unzip

install:
 - "pip install --pre -r requirements.txt"

python:
 - "3.4"
script:
 - sh -x test/opencv3_setup.sh
 - python main.py
